export enum CreditStatus {
  PENDING = 'PENDING',
  DELIVERED = 'DELIVERED',
  ACCEPTED = 'ACCEPTED',
  CANCELLED = 'CANCELLED',
  REJECTED = 'REJECTED',
  PROCESSED = 'PROCESSED',
  NOT_PAID = 'NOT_PAID',
  PAID = 'PAID',
  EDITED = 'EDITED',
}